# Generated by Django 4.1.6 on 2023-03-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], max_length=1)),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Testapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveSmallIntegerField()),
                ('Price', models.FloatField()),
                ('Room_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Testapp.room_type')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField()),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Testapp.room')),
            ],
        ),
    ]
